# Generated by Django 4.2.9 on 2024-03-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='discount_percent',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='dollar_discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='dollar discount amount'),
        ),
    ]
