# Generated by Django 4.2.9 on 2024-02-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, verbose_name='title (EN)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (EN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='./categories/covers', verbose_name='cover')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='./categories/icons', verbose_name='icon')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course.category', verbose_name='parent category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('title_en', models.CharField(max_length=256, verbose_name='title (EN)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description (EN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='./courses/covers', verbose_name='cover')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='./courses/icons', verbose_name='icon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.category', verbose_name='category')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.plan', verbose_name='plan')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='title (EN)')),
                ('video', models.FileField(upload_to='./courses/videos', verbose_name='video')),
                ('region', models.CharField(choices=[('INSIDE', 'INSIDE'), ('OUTSIDE', 'OUTSIDE')], verbose_name='region')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.course', verbose_name='for course')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='title (EN)')),
                ('pdf', models.FileField(upload_to='./courses/Pdfs', verbose_name='video')),
                ('region', models.CharField(choices=[('INSIDE', 'INSIDE'), ('OUTSIDE', 'OUTSIDE')], verbose_name='region')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='course.course', verbose_name='for course')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='title (EN)')),
                ('image', models.FileField(upload_to='./courses/images', verbose_name='video')),
                ('region', models.CharField(choices=[('INSIDE', 'INSIDE'), ('OUTSIDE', 'OUTSIDE')], verbose_name='region')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='course.course', verbose_name='for course')),
            ],
        ),
    ]
