# Generated by Django 4.2.9 on 2024-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='region',
            field=models.CharField(choices=[('ALL', 'ALL'), ('INSIDE', 'INSIDE'), ('OUTSIDE', 'OUTSIDE')], default='INSIDE', verbose_name='region'),
            preserve_default=False,
        ),
    ]
