# Generated by Django 4.2.9 on 2024-03-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_dollar_price_and_more'),
        ('course', '0004_remove_course_plan_course_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='plan',
        ),
        migrations.AddField(
            model_name='course',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.plan', verbose_name='plans'),
        ),
    ]
