# Generated by Django 4.2.9 on 2024-03-05 10:35

from django.db import migrations, models
import utils.validators.username_validator


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 128 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=128, null=True, unique=True, validators=[utils.validators.username_validator.UsernameValidator()], verbose_name='username'),
        ),
    ]
