# Generated by Django 4.2.9 on 2024-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='release date')),
                ('release_version', models.CharField(max_length=64, verbose_name='release version')),
                ('is_deprecate', models.BooleanField(default=False, verbose_name=' is deprecate')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last_name')),
                ('phone_number', models.CharField(max_length=128, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, verbose_name='title (EN)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(verbose_name='description (EN)')),
                ('button_text', models.CharField(max_length=128, verbose_name='button text')),
                ('button_link', models.CharField(max_length=256, verbose_name='button url')),
            ],
        ),
    ]
