# Generated by Django 4.2.9 on 2024-02-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
    ]
