# Generated by Django 4.2.9 on 2024-03-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_contactus_phone_number_alter_contactus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='last name'),
        ),
    ]
