# Generated by Django 4.2.9 on 2024-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_contactus_first_name_alter_contactus_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='release_version',
            field=models.CharField(max_length=64, unique=True, verbose_name='release version'),
        ),
    ]
