# Generated by Django 4.2.9 on 2024-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, verbose_name='title (EN)')),
                ('message', models.TextField(verbose_name='message')),
                ('message_en', models.TextField(verbose_name='message (EN)')),
                ('user_type', models.CharField(choices=[('ALL', 'All Users'), ('FREE', 'Users Without Plan'), ('VIP', 'Users Whith Plan'), ('INSIDE', 'Users Inside Iran'), ('OUTSIDE', 'Users Outside Iran')], default='ALL', verbose_name='send for')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
