# Generated by Django 4.2.9 on 2024-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=256, unique=True, verbose_name='title (EN)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(verbose_name='descriptin (EN)')),
                ('duration', models.PositiveIntegerField(default=365, verbose_name='duration')),
                ('toman_price', models.PositiveIntegerField(verbose_name='toman price')),
                ('toman_price_discount', models.PositiveIntegerField(verbose_name='toman price discount')),
                ('dollar_price', models.PositiveIntegerField(verbose_name='dollar price')),
                ('dollar_price_discount', models.PositiveIntegerField(verbose_name='dollar price discount')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='./plans/covers', verbose_name='cover')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='./plans/icons', verbose_name='icon')),
            ],
        ),
    ]
