# Generated by Django 4.2.9 on 2024-02-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_en', models.CharField(max_length=128, verbose_name='title (EN)')),
                ('gateway_type', models.CharField(choices=[('PAYPAL', 'Paypal'), ('MELAT', 'Melat')], verbose_name='gateway type')),
                ('token', models.CharField(max_length=1024, verbose_name='token')),
                ('secret', models.CharField(blank=True, max_length=1024, null=True, verbose_name='secret')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='card number')),
                ('payment_number', models.CharField(max_length=128, verbose_name='payment number')),
                ('status', models.CharField(choices=[('PAYING', 'Paying'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='PAYING', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discountcode', verbose_name='discount code')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentgateway', verbose_name='gateway')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.plan', verbose_name='plan')),
            ],
        ),
    ]
