# Generated by Django 4.2.9 on 2024-02-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(default=1, max_length=128, verbose_name='invoice number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='gateway',
            field=models.CharField(choices=[('PAYPAL', 'Paypal'), ('PARSIAN', 'Parsian')], default=None, verbose_name='gateway'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
